const e = (emoji, name, keywords = []) => ({ emoji, name, keywords });

export const classLogoCategories = [
    {
        id: 'magic',
        label: 'Magic',
        icon: '🪄',
        items: [
            e('⭐', 'Star', ['star', 'sparkle', 'night', 'wish']),
            e('✨', 'Sparkles', ['magic', 'glitter', 'shine']),
            e('⚡', 'Lightning', ['bolt', 'power', 'energy', 'storm']),
            e('🔮', 'Crystal Ball', ['fortune', 'mystic', 'orb', 'future']),
            e('💍', 'Ring', ['jewel', 'treasure', 'magic']),
            e('🧙', 'Wizard', ['mage', 'sorcerer', 'magic', 'staff']),
            e('🧚', 'Fairy', ['pixie', 'wings', 'magic']),
            e('🧞', 'Genie', ['lamp', 'wish', 'magic']),
            e('🪄', 'Magic Wand', ['wand', 'spell', 'charm']),
            e('💫', 'Dizzy Star', ['spark', 'comet', 'magic']),
            e('🌟', 'Glowing Star', ['shine', 'bright', 'night']),
            e('🕯️', 'Candle', ['flame', 'light', 'spell']),
            e('🧿', 'Nazar Amulet', ['charm', 'protect', 'luck']),
            e('🎃', 'Jack-o-lantern', ['halloween', 'autumn', 'pumpkin']),
            e('👻', 'Ghost', ['spooky', 'halloween', 'spirit']),
            e('🧛', 'Vampire', ['night', 'cape', 'spooky']),
            e('🧝', 'Elf', ['fantasy', 'forest', 'magic']),
            e('🦸', 'Superhero', ['hero', 'cape', 'power']),
            e('🦹', 'Supervillain', ['villain', 'mask', 'power']),
            e('🎆', 'Fireworks', ['celebration', 'night', 'spark']),
            e('🎇', 'Sparkler', ['spark', 'celebration', 'night']),
            e('🎴', 'Flower Cards', ['cards', 'game', 'mystic']),
            e('🪬', 'Hamsa', ['amulet', 'protect', 'luck']),
            e('🦄', 'Unicorn', ['magic', 'horse', 'myth', 'rainbow'])
        ]
    },
    {
        id: 'adventure',
        label: 'Quest',
        icon: '🧭',
        items: [
            e('🧭', 'Compass', ['quest', 'explore', 'direction', 'map']),
            e('🗺️', 'World Map', ['map', 'explore', 'travel', 'quest']),
            e('🛡️', 'Shield', ['armor', 'guard', 'knight', 'protect']),
            e('⚔️', 'Crossed Swords', ['sword', 'battle', 'knight', 'quest']),
            e('🏹', 'Bow and Arrow', ['archer', 'hunt', 'quest']),
            e('🔱', 'Trident', ['sea', 'poseidon', 'weapon']),
            e('⚓', 'Anchor', ['ship', 'sea', 'navy']),
            e('🗝️', 'Old Key', ['key', 'secret', 'door', 'treasure']),
            e('🏰', 'Castle', ['fortress', 'kingdom', 'quest']),
            e('🏺', 'Amphora', ['vase', 'ancient', 'treasure']),
            e('⏳', 'Hourglass', ['time', 'sand', 'wait']),
            e('🕰️', 'Mantel Clock', ['time', 'vintage', 'clock']),
            e('🏔️', 'Snow Mountain', ['mountain', 'peak', 'climb']),
            e('⛰️', 'Mountain', ['peak', 'hike', 'adventure']),
            e('🏕️', 'Camping', ['camp', 'tent', 'outdoors']),
            e('⛺', 'Tent', ['camp', 'outdoors', 'sleep']),
            e('🗿', 'Moai', ['statue', 'island', 'ancient']),
            e('🏴‍☠️', 'Pirate Flag', ['pirate', 'treasure', 'ship']),
            e('🛶', 'Canoe', ['boat', 'river', 'paddle']),
            e('⛵', 'Sailboat', ['boat', 'sea', 'wind']),
            e('🚂', 'Locomotive', ['train', 'travel', 'engine']),
            e('🎒', 'Backpack', ['bag', 'school', 'hike', 'travel']),
            e('🪂', 'Parachute', ['sky', 'jump', 'air']),
            e('🪃', 'Boomerang', ['throw', 'australia', 'hunt']),
            e('🪓', 'Axe', ['wood', 'tool', 'adventure']),
            e('🏯', 'Japanese Castle', ['fortress', 'pagoda', 'kingdom']),
            e('🚁', 'Helicopter', ['air', 'rescue', 'fly']),
            e('🚲', 'Bicycle', ['bike', 'ride', 'sport']),
            e('🪖', 'Helmet', ['armor', 'guard', 'soldier']),
            e('✈️', 'Airplane', ['fly', 'travel', 'sky']),
            e('🗽', 'Statue of Liberty', ['statue', 'city', 'freedom']),
            e('🗼', 'Tokyo Tower', ['tower', 'city', 'landmark']),
            e('🎡', 'Ferris Wheel', ['fair', 'park', 'ride']),
            e('🎢', 'Roller Coaster', ['park', 'ride', 'thrill']),
            e('🌉', 'Bridge', ['city', 'night', 'river']),
            e('🚤', 'Speedboat', ['boat', 'sea', 'fast']),
            e('🗡️', 'Dagger', ['sword', 'blade', 'quest']),
            e('🛴', 'Scooter', ['ride', 'city', 'wheel']),
            e('🛹', 'Skateboard', ['ride', 'sport', 'wheel']),
            e('🥷', 'Ninja', ['stealth', 'warrior', 'quest']),
            e('🛖', 'Hut', ['cabin', 'village', 'camp']),
            e('🚢', 'Ship', ['boat', 'sea', 'voyage']),
            e('🚠', 'Cable Car', ['mountain', 'ride', 'travel'])
        ]
    },
    {
        id: 'learning',
        label: 'Learning',
        icon: '📚',
        items: [
            e('📚', 'Books', ['book', 'library', 'school', 'read']),
            e('📖', 'Open Book', ['book', 'read', 'story', 'school']),
            e('🖋️', 'Fountain Pen', ['write', 'ink', 'pen']),
            e('🧠', 'Brain', ['think', 'smart', 'mind']),
            e('💡', 'Light Bulb', ['idea', 'invent', 'smart']),
            e('🧩', 'Puzzle Piece', ['puzzle', 'think', 'fit']),
            e('📜', 'Scroll', ['paper', 'ancient', 'story']),
            e('🧮', 'Abacus', ['math', 'count', 'numbers']),
            e('🔔', 'Bell', ['school', 'ring', 'class']),
            e('📈', 'Rising Chart', ['growth', 'progress', 'math']),
            e('📝', 'Memo', ['notes', 'write', 'homework']),
            e('✏️', 'Pencil', ['write', 'draw', 'school']),
            e('📐', 'Triangle Ruler', ['math', 'geometry', 'draw']),
            e('📏', 'Ruler', ['math', 'measure', 'straight']),
            e('🎓', 'Graduation Cap', ['graduate', 'school', 'success']),
            e('📓', 'Notebook', ['notes', 'write', 'school']),
            e('📔', 'Decorative Notebook', ['notes', 'journal', 'write']),
            e('📒', 'Ledger', ['notes', 'account', 'book']),
            e('📕', 'Red Book', ['book', 'read', 'closed']),
            e('📗', 'Green Book', ['book', 'read', 'closed']),
            e('📘', 'Blue Book', ['book', 'read', 'closed']),
            e('📙', 'Orange Book', ['book', 'read', 'closed']),
            e('🔖', 'Bookmark', ['book', 'mark', 'read']),
            e('📌', 'Pushpin', ['pin', 'note', 'mark']),
            e('📋', 'Clipboard', ['list', 'notes', 'check']),
            e('📊', 'Bar Chart', ['graph', 'data', 'math']),
            e('🖊️', 'Pen', ['write', 'ink', 'notes']),
            e('🖍️', 'Crayon', ['draw', 'color', 'art']),
            e('✂️', 'Scissors', ['cut', 'craft', 'paper']),
            e('📁', 'Folder', ['files', 'organize', 'paper']),
            e('📅', 'Calendar', ['date', 'day', 'plan']),
            e('🗃️', 'File Box', ['files', 'organize', 'archive']),
            e('🔤', 'ABCs', ['letters', 'alphabet', 'read']),
            e('🔢', 'Numbers', ['math', 'count', 'digits']),
            e('💯', 'Hundred Points', ['perfect', 'score', 'yes']),
            e('📰', 'Newspaper', ['news', 'read', 'paper']),
            e('📎', 'Paperclip', ['clip', 'paper', 'office']),
            e('🏷️', 'Label', ['tag', 'name', 'mark']),
            e('📑', 'Bookmark Tabs', ['pages', 'mark', 'organize']),
            e('✒️', 'Nib', ['write', 'ink', 'calligraphy'])
        ]
    },
    {
        id: 'science',
        label: 'Science',
        icon: '🔬',
        items: [
            e('🧪', 'Test Tube', ['lab', 'chem', 'experiment']),
            e('🤖', 'Robot', ['bot', 'tech', 'future']),
            e('💻', 'Laptop', ['computer', 'code', 'tech']),
            e('🔭', 'Telescope', ['stars', 'space', 'look']),
            e('🔬', 'Microscope', ['lab', 'tiny', 'science']),
            e('⚙️', 'Gear', ['machine', 'build', 'engineer']),
            e('🧬', 'DNA', ['gene', 'life', 'biology']),
            e('⚗️', 'Alembic', ['chem', 'lab', 'potion']),
            e('⚛️', 'Atom', ['physics', 'science', 'particle']),
            e('🧲', 'Magnet', ['attract', 'science', 'pole']),
            e('📡', 'Satellite Dish', ['signal', 'space', 'radio']),
            e('🛰️', 'Satellite', ['space', 'orbit', 'tech']),
            e('🌡️', 'Thermometer', ['temp', 'heat', 'science']),
            e('🔋', 'Battery', ['power', 'energy', 'tech']),
            e('💾', 'Floppy Disk', ['save', 'data', 'computer']),
            e('🖥️', 'Desktop', ['computer', 'screen', 'tech']),
            e('⌨️', 'Keyboard', ['type', 'computer', 'code']),
            e('🖱️', 'Computer Mouse', ['click', 'computer', 'pointer']),
            e('🔌', 'Plug', ['power', 'electric', 'tech']),
            e('🔦', 'Flashlight', ['light', 'beam', 'dark']),
            e('🧰', 'Toolbox', ['tools', 'build', 'fix']),
            e('🪛', 'Screwdriver', ['tool', 'fix', 'build']),
            e('🔧', 'Wrench', ['tool', 'fix', 'build']),
            e('🪚', 'Saw', ['tool', 'wood', 'build']),
            e('🧱', 'Brick', ['build', 'wall', 'block']),
            e('🧫', 'Petri Dish', ['lab', 'biology', 'culture']),
            e('🦠', 'Microbe', ['germ', 'biology', 'tiny']),
            e('🧯', 'Extinguisher', ['fire', 'safety', 'lab']),
            e('🖨️', 'Printer', ['print', 'paper', 'computer'])
        ]
    },
    {
        id: 'creatures',
        label: 'Creatures',
        icon: '🦁',
        items: [
            e('🦁', 'Lion', ['cat', 'king', 'animal', 'wild']),
            e('🐲', 'Dragon Face', ['dragon', 'myth', 'creature']),
            e('🦉', 'Owl', ['wise', 'bird', 'night']),
            e('🦊', 'Fox', ['clever', 'animal', 'wild']),
            e('🦖', 'T-Rex', ['dino', 'dinosaur', 'giant']),
            e('🦕', 'Sauropod', ['dino', 'dinosaur', 'long']),
            e('🐢', 'Turtle', ['slow', 'shell', 'animal']),
            e('🦋', 'Butterfly', ['wings', 'insect', 'pretty']),
            e('🦅', 'Eagle', ['bird', 'fly', 'sky']),
            e('🐺', 'Wolf', ['wild', 'pack', 'howl']),
            e('🐼', 'Panda', ['bear', 'bamboo', 'cute']),
            e('🐨', 'Koala', ['bear', 'australia', 'cute']),
            e('🦡', 'Badger', ['animal', 'burrow', 'wild']),
            e('🦔', 'Hedgehog', ['spines', 'small', 'animal']),
            e('🦚', 'Peacock', ['bird', 'feather', 'pretty']),
            e('🧜‍♀️', 'Mermaid', ['sea', 'myth', 'fish']),
            e('🐉', 'Dragon', ['dragon', 'myth', 'creature', 'eastern']),
            e('🐯', 'Tiger', ['cat', 'stripes', 'wild']),
            e('🐻', 'Bear', ['animal', 'forest', 'wild']),
            e('🐸', 'Frog', ['pond', 'jump', 'green']),
            e('🐧', 'Penguin', ['bird', 'ice', 'cold']),
            e('🐙', 'Octopus', ['sea', 'arms', 'smart']),
            e('🐬', 'Dolphin', ['sea', 'smart', 'swim']),
            e('🐳', 'Whale', ['sea', 'giant', 'ocean']),
            e('🦈', 'Shark', ['sea', 'teeth', 'ocean']),
            e('🐝', 'Bee', ['honey', 'buzz', 'insect']),
            e('🐞', 'Ladybug', ['insect', 'spots', 'lucky']),
            e('🐍', 'Snake', ['reptile', 'slither', 'wild']),
            e('🦎', 'Lizard', ['reptile', 'desert', 'wild']),
            e('🦒', 'Giraffe', ['tall', 'spots', 'africa']),
            e('🦓', 'Zebra', ['stripes', 'horse', 'africa']),
            e('🐘', 'Elephant', ['giant', 'trunk', 'africa']),
            e('🦘', 'Kangaroo', ['jump', 'australia', 'pouch']),
            e('🦥', 'Sloth', ['slow', 'tree', 'cute']),
            e('🦦', 'Otter', ['river', 'play', 'swim']),
            e('🦩', 'Flamingo', ['bird', 'pink', 'stand']),
            e('🦜', 'Parrot', ['bird', 'talk', 'color']),
            e('🐣', 'Hatching Chick', ['bird', 'baby', 'egg']),
            e('🐰', 'Rabbit', ['bunny', 'hop', 'cute']),
            e('🐹', 'Hamster', ['small', 'pet', 'cute']),
            e('🐱', 'Cat', ['kitten', 'pet', 'meow']),
            e('🐶', 'Dog', ['puppy', 'pet', 'friend']),
            e('🦀', 'Crab', ['sea', 'pinch', 'shell']),
            e('🦑', 'Squid', ['sea', 'ink', 'ocean']),
            e('🦭', 'Seal', ['sea', 'ice', 'cute']),
            e('🦂', 'Scorpion', ['desert', 'sting', 'wild']),
            e('🐵', 'Monkey', ['banana', 'tree', 'play']),
            e('🦇', 'Bat', ['night', 'cave', 'fly']),
            e('🐻‍❄️', 'Polar Bear', ['bear', 'ice', 'arctic']),
            e('🦝', 'Raccoon', ['mask', 'night', 'clever']),
            e('🐊', 'Crocodile', ['river', 'teeth', 'reptile']),
            e('🐗', 'Boar', ['wild', 'tusk', 'forest']),
            e('🦌', 'Deer', ['forest', 'antler', 'gentle']),
            e('🐎', 'Horse', ['ride', 'fast', 'stable']),
            e('🐷', 'Pig', ['farm', 'pink', 'cute']),
            e('🦙', 'Llama', ['andes', 'wool', 'spit']),
            e('🐁', 'Mouse', ['small', 'cheese', 'quiet']),
            e('🐿️', 'Chipmunk', ['nuts', 'forest', 'small']),
            e('🦫', 'Beaver', ['dam', 'river', 'wood']),
            e('🦤', 'Dodo', ['bird', 'extinct', 'island']),
            e('🦣', 'Mammoth', ['giant', 'ice', 'tusk']),
            e('🦢', 'Swan', ['bird', 'lake', 'grace']),
            e('🦆', 'Duck', ['bird', 'pond', 'quack']),
            e('🐡', 'Blowfish', ['fish', 'sea', 'puff']),
            e('🐠', 'Tropical Fish', ['fish', 'sea', 'color']),
            e('🐟', 'Fish', ['sea', 'swim', 'water']),
            e('🦞', 'Lobster', ['sea', 'claw', 'red']),
            e('🦐', 'Shrimp', ['sea', 'small', 'pink']),
            e('🕷️', 'Spider', ['web', 'insect', 'eight']),
            e('🐛', 'Bug', ['insect', 'caterpillar', 'garden']),
            e('🦗', 'Cricket', ['insect', 'chirp', 'garden']),
            e('🪲', 'Beetle', ['insect', 'shell', 'garden']),
            e('🐔', 'Chicken', ['farm', 'bird', 'egg'])
        ]
    },
    {
        id: 'nature',
        label: 'Nature',
        icon: '🌿',
        items: [
            e('🌍', 'Globe Europe', ['earth', 'world', 'planet']),
            e('🌲', 'Evergreen', ['tree', 'forest', 'pine']),
            e('🌊', 'Wave', ['ocean', 'sea', 'water']),
            e('🌋', 'Volcano', ['lava', 'erupt', 'mountain']),
            e('🍄', 'Mushroom', ['forest', 'toadstool', 'fungus']),
            e('🌵', 'Cactus', ['desert', 'plant', 'spines']),
            e('🍁', 'Maple Leaf', ['autumn', 'canada', 'fall']),
            e('🐚', 'Seashell', ['beach', 'ocean', 'spiral']),
            e('🌱', 'Seedling', ['grow', 'plant', 'sprout']),
            e('🌈', 'Rainbow', ['color', 'sky', 'hope']),
            e('🗻', 'Mount Fuji', ['mountain', 'japan', 'peak']),
            e('🌳', 'Deciduous Tree', ['tree', 'forest', 'shade']),
            e('🌴', 'Palm Tree', ['beach', 'tropical', 'island']),
            e('🍀', 'Four Leaf Clover', ['luck', 'green', 'irish']),
            e('🌸', 'Cherry Blossom', ['flower', 'spring', 'pink']),
            e('🌺', 'Hibiscus', ['flower', 'tropical', 'pretty']),
            e('🌻', 'Sunflower', ['flower', 'sun', 'yellow']),
            e('🌼', 'Blossom', ['flower', 'spring', 'yellow']),
            e('🌷', 'Tulip', ['flower', 'spring', 'garden']),
            e('🌹', 'Rose', ['flower', 'love', 'red']),
            e('🌾', 'Rice Sheaf', ['grain', 'farm', 'field']),
            e('🌿', 'Herb', ['leaf', 'green', 'plant']),
            e('🍃', 'Fluttering Leaf', ['wind', 'green', 'tree']),
            e('🍂', 'Fallen Leaf', ['autumn', 'fall', 'orange']),
            e('🪴', 'Potted Plant', ['plant', 'grow', 'home']),
            e('🪨', 'Rock', ['stone', 'boulder', 'solid']),
            e('💧', 'Droplet', ['water', 'rain', 'drop']),
            e('❄️', 'Snowflake', ['cold', 'winter', 'ice']),
            e('⛄', 'Snowman', ['winter', 'cold', 'snow']),
            e('🔥', 'Fire', ['flame', 'hot', 'camp']),
            e('🌪️', 'Tornado', ['storm', 'wind', 'spin']),
            e('🌏', 'Globe Asia', ['earth', 'world', 'planet']),
            e('🌎', 'Globe Americas', ['earth', 'world', 'planet']),
            e('🏞️', 'National Park', ['valley', 'nature', 'view']),
            e('🏜️', 'Desert', ['sand', 'hot', 'cactus']),
            e('🏝️', 'Desert Island', ['beach', 'palm', 'alone']),
            e('⛲', 'Fountain', ['water', 'park', 'splash']),
            e('🎋', 'Tanabata Tree', ['bamboo', 'wish', 'festival']),
            e('🎄', 'Christmas Tree', ['holiday', 'winter', 'pine']),
            e('💐', 'Bouquet', ['flowers', 'gift', 'pretty']),
            e('🥀', 'Wilted Flower', ['rose', 'sad', 'old']),
            e('🪷', 'Lotus', ['flower', 'calm', 'water']),
            e('⛅', 'Sun Behind Cloud', ['weather', 'cloud', 'day']),
            e('🌦️', 'Sun Behind Rain', ['weather', 'rain', 'sun']),
            e('🌧️', 'Rain Cloud', ['weather', 'rain', 'storm']),
            e('⛈️', 'Thunderstorm', ['weather', 'storm', 'lightning']),
            e('🌩️', 'Lightning Cloud', ['weather', 'storm', 'bolt']),
            e('🌨️', 'Snow Cloud', ['weather', 'snow', 'winter']),
            e('🌤️', 'Small Cloud Sun', ['weather', 'sun', 'day']),
            e('🕸️', 'Spider Web', ['web', 'halloween', 'silk']),
            e('🪸', 'Coral', ['reef', 'ocean', 'sea']),
            e('🪵', 'Wood', ['log', 'forest', 'tree'])
        ]
    },
    {
        id: 'sky',
        label: 'Sky & Space',
        icon: '🚀',
        items: [
            e('🚀', 'Rocket', ['space', 'launch', 'fly']),
            e('🌙', 'Crescent Moon', ['night', 'sky', 'sleep']),
            e('☀️', 'Sun', ['day', 'hot', 'sky']),
            e('☁️', 'Cloud', ['sky', 'weather', 'soft']),
            e('🌃', 'Night City', ['city', 'stars', 'night']),
            e('🌆', 'Dusk City', ['city', 'sunset', 'skyline']),
            e('🏙️', 'Cityscape', ['city', 'buildings', 'skyline']),
            e('🛸', 'Flying Saucer', ['alien', 'ufo', 'space']),
            e('🪐', 'Ringed Planet', ['saturn', 'space', 'planet']),
            e('🌌', 'Milky Way', ['galaxy', 'stars', 'space']),
            e('🌠', 'Shooting Star', ['wish', 'meteor', 'night']),
            e('🌑', 'New Moon', ['night', 'dark', 'sky']),
            e('🌕', 'Full Moon', ['night', 'sky', 'bright']),
            e('🌚', 'New Moon Face', ['night', 'moon', 'face']),
            e('🌝', 'Full Moon Face', ['night', 'moon', 'face']),
            e('🌞', 'Sun Face', ['day', 'sun', 'smile']),
            e('🌛', 'First Quarter Moon', ['night', 'moon', 'face']),
            e('🌜', 'Last Quarter Moon', ['night', 'moon', 'face']),
            e('☄️', 'Comet', ['space', 'tail', 'sky'])
        ]
    },
    {
        id: 'arts',
        label: 'Arts & Play',
        icon: '🎨',
        items: [
            e('🎨', 'Palette', ['art', 'paint', 'color']),
            e('🪁', 'Kite', ['wind', 'fly', 'play']),
            e('🪀', 'Yo-yo', ['toy', 'play', 'string']),
            e('👾', 'Alien Monster', ['game', 'arcade', 'pixel']),
            e('🎭', 'Masks', ['theater', 'drama', 'play']),
            e('🎪', 'Circus Tent', ['show', 'circus', 'fun']),
            e('🎬', 'Clapper Board', ['movie', 'film', 'action']),
            e('🎤', 'Microphone', ['sing', 'stage', 'voice']),
            e('🎧', 'Headphones', ['music', 'listen', 'audio']),
            e('🎼', 'Musical Score', ['music', 'notes', 'sheet']),
            e('🎹', 'Piano', ['keyboard', 'music', 'keys']),
            e('🥁', 'Drum', ['music', 'beat', 'band']),
            e('🎸', 'Guitar', ['music', 'band', 'rock']),
            e('🎺', 'Trumpet', ['music', 'brass', 'band']),
            e('🎻', 'Violin', ['music', 'strings', 'orchestra']),
            e('🎷', 'Saxophone', ['music', 'jazz', 'band']),
            e('🎲', 'Die', ['game', 'luck', 'random']),
            e('🎮', 'Controller', ['game', 'play', 'video']),
            e('🕹️', 'Joystick', ['game', 'arcade', 'play']),
            e('♟️', 'Chess Pawn', ['game', 'chess', 'strategy']),
            e('🧸', 'Teddy Bear', ['toy', 'cute', 'friend']),
            e('🪆', 'Nesting Dolls', ['doll', 'russia', 'toy']),
            e('🎵', 'Music Note', ['song', 'sound', 'melody']),
            e('🎶', 'Music Notes', ['song', 'sound', 'melody']),
            e('📷', 'Camera', ['photo', 'picture', 'snap']),
            e('🎥', 'Movie Camera', ['film', 'video', 'cinema']),
            e('🖼️', 'Framed Picture', ['art', 'gallery', 'photo']),
            e('🪡', 'Needle', ['sew', 'craft', 'thread']),
            e('🧵', 'Thread', ['sew', 'craft', 'spool']),
            e('🧶', 'Yarn', ['knit', 'craft', 'wool']),
            e('🪕', 'Banjo', ['music', 'strings', 'folk']),
            e('🪘', 'Long Drum', ['music', 'beat', 'percussion']),
            e('📻', 'Radio', ['music', 'listen', 'broadcast']),
            e('📺', 'Television', ['tv', 'show', 'watch'])
        ]
    },
    {
        id: 'sports',
        label: 'Sports',
        icon: '⚽',
        items: [
            e('🏀', 'Basketball', ['ball', 'hoop', 'sport']),
            e('⚽', 'Soccer Ball', ['football', 'goal', 'sport']),
            e('🏈', 'American Football', ['ball', 'sport', 'touchdown']),
            e('⚾', 'Baseball', ['ball', 'bat', 'sport']),
            e('🎾', 'Tennis', ['ball', 'racket', 'sport']),
            e('🏐', 'Volleyball', ['ball', 'net', 'sport']),
            e('🏉', 'Rugby', ['ball', 'sport', 'scrum']),
            e('🥏', 'Flying Disc', ['frisbee', 'throw', 'sport']),
            e('🏓', 'Ping Pong', ['table', 'paddle', 'sport']),
            e('🏸', 'Badminton', ['shuttle', 'racket', 'sport']),
            e('🥊', 'Boxing Glove', ['punch', 'fight', 'sport']),
            e('🥋', 'Martial Arts', ['karate', 'judo', 'gi']),
            e('⛳', 'Golf Flag', ['golf', 'hole', 'sport']),
            e('🎿', 'Skis', ['snow', 'winter', 'sport']),
            e('⛸️', 'Ice Skate', ['ice', 'winter', 'sport']),
            e('🥌', 'Curling Stone', ['ice', 'winter', 'sport']),
            e('🎣', 'Fishing Pole', ['fish', 'hook', 'lake']),
            e('🎯', 'Bullseye', ['target', 'dart', 'aim']),
            e('🎳', 'Bowling', ['pins', 'strike', 'sport']),
            e('🥍', 'Lacrosse', ['stick', 'ball', 'sport']),
            e('🏑', 'Field Hockey', ['stick', 'ball', 'sport']),
            e('🏒', 'Ice Hockey', ['puck', 'stick', 'ice']),
            e('🏏', 'Cricket', ['bat', 'ball', 'sport']),
            e('🛷', 'Sled', ['snow', 'winter', 'ride']),
            e('🏂', 'Snowboard', ['snow', 'winter', 'sport'])
        ]
    },
    {
        id: 'victory',
        label: 'Victory',
        icon: '🏆',
        items: [
            e('🏆', 'Trophy', ['win', 'prize', 'champion']),
            e('👑', 'Crown', ['king', 'queen', 'royal']),
            e('💎', 'Gem', ['jewel', 'treasure', 'shine']),
            e('🥇', 'Gold Medal', ['first', 'win', 'prize']),
            e('💥', 'Collision', ['boom', 'power', 'impact']),
            e('💰', 'Money Bag', ['gold', 'treasure', 'rich']),
            e('🥈', 'Silver Medal', ['second', 'prize', 'win']),
            e('🥉', 'Bronze Medal', ['third', 'prize', 'win']),
            e('🎖️', 'Military Medal', ['honor', 'prize', 'ribbon']),
            e('🏅', 'Sports Medal', ['prize', 'win', 'honor']),
            e('🎁', 'Gift', ['present', 'box', 'surprise']),
            e('🎉', 'Party Popper', ['celebrate', 'win', 'confetti']),
            e('🎊', 'Confetti Ball', ['celebrate', 'party', 'win']),
            e('🎈', 'Balloon', ['party', 'float', 'celebrate']),
            e('🎏', 'Carp Streamer', ['festival', 'wind', 'celebrate']),
            e('🪙', 'Coin', ['gold', 'money', 'treasure']),
            e('🎀', 'Ribbon', ['bow', 'gift', 'pretty']),
            e('💝', 'Heart Gift', ['love', 'gift', 'box']),
            e('💠', 'Diamond Dot', ['jewel', 'pattern', 'shine'])
        ]
    },
    {
        id: 'treats',
        label: 'Treats',
        icon: '🍎',
        items: [
            e('🍎', 'Red Apple', ['fruit', 'school', 'teacher']),
            e('🍏', 'Green Apple', ['fruit', 'school', 'fresh']),
            e('🍊', 'Tangerine', ['fruit', 'orange', 'citrus']),
            e('🍋', 'Lemon', ['fruit', 'citrus', 'sour']),
            e('🍌', 'Banana', ['fruit', 'yellow', 'monkey']),
            e('🍉', 'Watermelon', ['fruit', 'summer', 'seed']),
            e('🍇', 'Grapes', ['fruit', 'vine', 'purple']),
            e('🍓', 'Strawberry', ['fruit', 'berry', 'red']),
            e('🍒', 'Cherries', ['fruit', 'pair', 'red']),
            e('🍑', 'Peach', ['fruit', 'soft', 'pink']),
            e('🍕', 'Pizza', ['food', 'slice', 'cheese']),
            e('🍩', 'Doughnut', ['sweet', 'snack', 'ring']),
            e('🍪', 'Cookie', ['sweet', 'snack', 'bake']),
            e('🧁', 'Cupcake', ['sweet', 'cake', 'frosting']),
            e('🎂', 'Birthday Cake', ['party', 'cake', 'candles']),
            e('🍦', 'Soft Ice Cream', ['sweet', 'cold', 'cone']),
            e('🍭', 'Lollipop', ['candy', 'sweet', 'stick']),
            e('🍿', 'Popcorn', ['snack', 'movie', 'corn']),
            e('🧋', 'Bubble Tea', ['drink', 'tea', 'pearl']),
            e('🌮', 'Taco', ['food', 'shell', 'spicy']),
            e('🥨', 'Pretzel', ['snack', 'twist', 'salt']),
            e('🧀', 'Cheese', ['food', 'dairy', 'yellow']),
            e('🥑', 'Avocado', ['fruit', 'green', 'toast']),
            e('🥕', 'Carrot', ['veggie', 'orange', 'rabbit']),
            e('🌽', 'Corn', ['veggie', 'farm', 'yellow']),
            e('🍫', 'Chocolate', ['sweet', 'bar', 'cocoa']),
            e('🍬', 'Candy', ['sweet', 'wrapper', 'sugar']),
            e('🥐', 'Croissant', ['bread', 'bake', 'butter']),
            e('🥞', 'Pancakes', ['breakfast', 'stack', 'syrup']),
            e('🧇', 'Waffle', ['breakfast', 'grid', 'syrup']),
            e('🍔', 'Hamburger', ['food', 'burger', 'lunch']),
            e('🍟', 'Fries', ['food', 'potato', 'snack']),
            e('🥭', 'Mango', ['fruit', 'tropical', 'sweet']),
            e('🍍', 'Pineapple', ['fruit', 'tropical', 'spiky']),
            e('🥝', 'Kiwi', ['fruit', 'green', 'seeds']),
            e('🥥', 'Coconut', ['fruit', 'tropical', 'shell']),
            e('🫐', 'Blueberries', ['fruit', 'berry', 'blue']),
            e('🍅', 'Tomato', ['veggie', 'red', 'sauce']),
            e('🥦', 'Broccoli', ['veggie', 'green', 'tree']),
            e('🍨', 'Ice Cream', ['sweet', 'cold', 'bowl']),
            e('🍧', 'Shaved Ice', ['sweet', 'cold', 'snow']),
            e('🥧', 'Pie', ['bake', 'sweet', 'slice']),
            e('🍰', 'Shortcake', ['cake', 'slice', 'sweet'])
        ]
    }
];

function stripVariantSelectors(value) {
    return [...String(value)].filter((char) => char.codePointAt(0) !== 0xFE0F).join('');
}

function itemMatchesQuery(item, category, query) {
    if (item.emoji.toLowerCase().includes(query)) return true;
    if (item.name.toLowerCase().includes(query)) return true;
    if (category.label.toLowerCase().includes(query)) return true;
    if (category.id.toLowerCase().includes(query)) return true;
    return item.keywords.some((keyword) => String(keyword).toLowerCase().includes(query));
}

export const classLogos = classLogoCategories.flatMap((category) => category.items.map((item) => item.emoji));

const classLogoSet = new Set(classLogos);
const classLogoNormalizedSet = new Set(classLogos.map(stripVariantSelectors));

export function isKnownClassLogo(logo) {
    if (classLogoSet.has(logo)) return true;
    return classLogoNormalizedSet.has(stripVariantSelectors(logo));
}

export function filterClassLogoCatalog(query = '', categoryId = 'all') {
    const needle = String(query || '').trim().toLowerCase();
    const categories = categoryId && categoryId !== 'all'
        ? classLogoCategories.filter((category) => category.id === categoryId)
        : classLogoCategories;
    return categories
        .map((category) => ({
            ...category,
            items: needle
                ? category.items.filter((item) => itemMatchesQuery(item, category, needle))
                : category.items
        }))
        .filter((category) => category.items.length > 0);
}
